import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const downloadAsPDF = (text: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const maxWidth = pageWidth - (margin * 2);
  
  // Setup document style
  doc.setFont('times', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 20);
  
  // Title/Header
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Word Lab", margin, 15);
  
  // Reset for body
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);

  // Split text to fit width
  const lines = doc.splitTextToSize(text, maxWidth);
  
  let cursorY = margin + 10;
  const lineHeight = 7;
  
  lines.forEach((line: string) => {
    // Check for page break
    if (cursorY + lineHeight > pageHeight - margin) {
      doc.addPage();
      cursorY = margin;
      
      // Header on new pages
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text("Word Lab", margin, 15);
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      cursorY += 10;
    }
    
    doc.text(line, margin, cursorY);
    cursorY += lineHeight;
  });
  
  doc.save('WordLab-document.pdf');
};

export const downloadAsJPG = async (text: string) => {
    // Create a temporary container to render the text as it looks in a document
    // We cannot capture the textarea directly perfectly because of scrollbars
    const container = document.createElement('div');
    
    // Style the container to look like a clean paper document
    Object.assign(container.style, {
      position: 'fixed',
      top: '-9999px',
      left: '-9999px',
      width: '800px', // Fixed width for A4-like ratio
      minHeight: '1000px',
      padding: '60px',
      backgroundColor: '#ffffff',
      fontFamily: '"Georgia", "Times New Roman", serif',
      fontSize: '18px',
      lineHeight: '1.8',
      color: '#1a1a1a',
      whiteSpace: 'pre-wrap', // Preserve newlines and spacing
      boxSizing: 'border-box',
      display: 'block'
    });

    // Add a footer watermark
    const content = document.createElement('div');
    content.innerText = text;
    container.appendChild(content);

    const footer = document.createElement('div');
    footer.innerText = "Generated with WordLab";
    Object.assign(footer.style, {
      marginTop: '40px',
      borderTop: '1px solid #eee',
      paddingTop: '10px',
      fontSize: '12px',
      color: '#999',
      fontFamily: 'sans-serif',
      textAlign: 'center'
    });
    container.appendChild(footer);
    
    document.body.appendChild(container);
    
    try {
        const canvas = await html2canvas(container, {
            scale: 2, // Retina quality
            backgroundColor: '#ffffff',
            logging: false
        });
        
        const link = document.createElement('a');
        link.download = 'WordLab.jpg';
        link.href = canvas.toDataURL('image/jpeg', 0.9);
        link.click();
    } catch (error) {
        console.error("Export failed", error);
        alert("Failed to generate image. Please try again.");
    } finally {
        document.body.removeChild(container);
    }
};